spring:
  application:
    name: User-project-ms
  config:
#    activate:
#      on-profile: dev
    import:
      optional:
        configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true