server:
  port: 8082

spring:
  application:
    name: Projects-ms
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: project_managementDB
