spring:
  application:
    name: Users-ms
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: project_managementDB

management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics #, metrics # "*" # health, env, info
  endpoint:
    health:
      show-details: always
