server:
  port: 8765


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Users-ms
          uri: http://127.0.0.1:8081/
          predicates:
            - Path=/users/**
        - id: Projects-ms
          uri: http://127.0.0.1:8082/
          predicates:
            - Path=/projects/**
        - id: User-project-ms
          uri: http://127.0.0.1:8083/
          predicates:
            - Path=/user-project/**
