/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw1gradleproject;

import java.sql.Date;
import java.time.LocalDate;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {


        Person ivan = new Person("Иван","Грознов", 493);
        Person petr = new Person("Петр","Первов", 351);

//        Person.saveJSON("leaders.json",ivan);
//        Person.saveJSON("leaders.json",petr);

        Person.readJSON("leaders.json").stream()
                .forEach(System.out::println);


    }
}
