server:
  port: 8081

spring:
  application:
    name: Users-ms
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: project_managementDB