
version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/home/maka/GeekBrains/_Tempor_installs/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/home/maka/GeekBrains/_Tempor_installs/prometheus
      - prom_data:/prometheus
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/home/maka/GeekBrains/_Tempor_installs/grafana
volumes:
  prom_data:
